In [52]:
import pandas as pd

# Load the dataset
df = pd.read_csv('data/dashboard-export-02-51-am-2024-11-30.csv')
df = df[df["Q28 - The University of Waikato and Tauranga City Council are undertakinga resear..."] == "Yes"]

# Define a mapping for age brackets to numeric values for easier processing
age_map = {
    'Under 16': 0,
    '16-24': 1,
    '25-34': 2,
    '35-44': 3,
    '45-54': 4,
    '55-64': 5,
    '65-74': 6,
    '75-84': 7,
    '85+': 8,
    'Prefer not to say': 9  # Handle 'Prefer not to say' category
}

age_brackets = ['16-24', '25-34', '35-44', '45-54', '55-64', '65-74', '75-84', '85+']

# Apply the mapping to the 'Age' column
df['Age_Num'] = df['Q26 - Age: *'].map(age_map)

# Number of groups you want to create
num_groups = 4

# Number of people in each group
group_size = 5

df["Group_Num"] = "None"

# Create empty groups
groups = {i: [] for i in range(num_groups)}

current_group = 0
current_age = 1 # Skip under 16s
# For each group, add the youngest person until the groups are full
# Results in spread of ages in each group (16-24 is added to group 0, then group 1, etc)
for i in range(len(age_map)):
    for _, row in df.iterrows():
        if row['Age_Num'] == current_age and len(groups[current_group]) < group_size:
            row['Group_Num'] = current_group # Assign group number
            groups[current_group].append(row) # Add person to group
            current_group = (current_group + 1) % num_groups

    current_age = current_age + 1

# Print the people in each group
for group_num, group_members in groups.items():
    print(f"Group {group_num}:")
    for person in group_members:
        fname = person['Q29 - First name: *']
        lname = person['Q30 - Last name: *']
        age = person['Q26 - Age: *']
        gender = person['Q27 - Gender: *']

        print(f"  {fname} {lname}, {age}, {gender}")

    # Show demographics in group
    group_df = pd.concat(group_members) # Convert to Pandas series to perform calc
    print((group_df['Q27 - Gender: *'].value_counts(normalize=True) * 100).to_string(index=True))
    print((group_df['Q26 - Age: *'].value_counts(normalize=True).reindex(age_brackets, fill_value=0) * 100).to_string(index=True)) # Include missing ages
    print()  # Add a blank line between groups

unassigned = df[df['Group_Num'] == "None"]

Group 0:
  Amber Fort, 16-24, Female
  Lisa Blazey, 35-44, Female
  Jonathan Simpson, 35-44, Male
  Aaron Paki, 45-54, Male
  Tim Searle, 45-54, Male
Male      60.0
Female    40.0
16-24    20.0
25-34     0.0
35-44    40.0
45-54    40.0
55-64     0.0
65-74     0.0
75-84     0.0
85+       0.0

Group 1:
  Amy Burgess, 16-24, Female
  Kelly Mead, 35-44, Female
  Rob Porter, 35-44, Male
  Devon Gillam, 45-54, Male
  Ivan Cole, 45-54, Male
Male      60.0
Female    40.0
16-24    20.0
25-34     0.0
35-44    40.0
45-54    40.0
55-64     0.0
65-74     0.0
75-84     0.0
85+       0.0

Group 2:
  Becky Pitt, 25-34, Female
  Darryl Forbes, 35-44, Male
  Lauren Bradley, 35-44, Female
  kate  rhodes, 45-54, Female
  Nicola Mulgrew, 45-54, Female
Female    80.0
Male      20.0
16-24     0.0
25-34    20.0
35-44    40.0
45-54    40.0
55-64     0.0
65-74     0.0
75-84     0.0
85+       0.0

Group 3:
  Emma-Leigh Hodge, 25-34, Female
  Adam Richardson, 35-44, Male
  David Hodge, 45-54, Male
  Lee Martin, 45-54, Female
  Ashok Harridaw, 45-54, Male
Male      60.0
Female    40.0
16-24     0.0
25-34    20.0
35-44    20.0
45-54    60.0
55-64     0.0
65-74     0.0
75-84     0.0
85+       0.0